# Generated by Django 4.1.7 on 2023-03-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_address_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='profiles.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='profiles.address'),
        ),
    ]
