from django.urls import path
from .views import (ProductUpdateView, CoffeeUpdateView, DepartmentCreateView,
                    DepartmentDeleteView, DepartmentUpdateView,
                    ManageShopView, ProductCreateView, CategoryDeleteView,
                    CategoryUpdateView, CategoryCreateView, CoffeeCreateView,
                    ProductDeleteView, ManageProductsView, BrandCreateView,
                    BrandUpdateView, BrandDeleteView, StaffOrderListView,
                    OrderDispatchView, PurgeStaleCartsView)

urlpatterns = [
    path("", ManageShopView.as_view(),
         name="manage_shop"),
    path("department/new/", DepartmentCreateView.as_view(),
         name="department_create"),
    path("department/<int:pk>/delete/",
         DepartmentDeleteView.as_view(), name="department_delete"),
    path("department/<int:pk>/update/", DepartmentUpdateView.as_view(),
         name="department_update"),
    path("products/", ManageProductsView.as_view(),
         name="manage_products"),
    path("c/<category>/",
         ManageProductsView.as_view(), name="manage_products_by_category"),
    path("d/<department>/",
         ManageProductsView.as_view(), name="manage_products_by_department"),
    path("category/new/", CategoryCreateView.as_view(),
         name="category_create"),
    path("category/<int:pk>/delete/",
         CategoryDeleteView.as_view(), name="category_delete"),
    path("category/<int:pk>/update/", CategoryUpdateView.as_view(),
         name="category_update"),
    path("brand/new/", BrandCreateView.as_view(),
         name="brand_create"),
    path("brand/<int:pk>/delete/",
         BrandDeleteView.as_view(), name="brand_delete"),
    path("brand/<int:pk>/update/", BrandUpdateView.as_view(),
         name="brand_update"),
    path("product/<slug:slug>/update/",
         ProductUpdateView.as_view(), name="product_update"),
    path("coffee/<slug:slug>/update/",
         CoffeeUpdateView.as_view(), name="coffee_update"),
    path("new/product", ProductCreateView.as_view(),
         name="product_create"),
    path("new/coffee", CoffeeCreateView.as_view(), name="coffee_create"),
    path("product/<int:pk>/delete/",
         ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", StaffOrderListView.as_view(), name="manage_orders"),
    path("order/<str:order_number>/dispatch",
         OrderDispatchView.as_view(), name="order_dispatched"),
    path("carts/purge", PurgeStaleCartsView.as_view(),
         name='purge_stale_carts'),
]
