# Generated by Django 4.1.7 on 2023-03-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_lifetime_sales_alter_product_sku'),
        ('checkout', '0005_orderitem_total_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('grind_size', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('product_name', models.CharField(blank=True, editable=False, max_length=254, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='checkout.order'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
