# Generated by Django 4.1.7 on 2023-03-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_order_grand_total_remove_order_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_placed_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
