from django.urls import path
from .views import (ProductsList, ProductUpdate,
                    CoffeeUpdate, DepartmentCreate, DepartmentDelete,
                    DepartmentUpdate, ManageCategories, product_detail,
                    ProductCreate, CategoryDelete, CategoryUpdate,
                    CategoryCreate, CoffeeCreate, ProductDelete,
                    ManageProducts)

urlpatterns = [
    path("", ProductsList.as_view(), name="products"),
    path("c/<category>/",
         ProductsList.as_view(), name="products_by_category"),
    path("d/<department>/",
         ProductsList.as_view(), name="products_by_department"),
    path("b/<brand>/",
         ProductsList.as_view(), name="products_by_brand"),
    path("item/<slug:slug>", product_detail, name="product_detail"),
    path("staff/department/new/", DepartmentCreate.as_view(),
         name="department_create"),
    path("staff/department/<int:pk>/delete/",
         DepartmentDelete.as_view(), name="department_delete"),
    path("staff/department/<int:pk>/update/", DepartmentUpdate.as_view(),
         name="department_update"),
    path("staff/", ManageCategories.as_view(),
         name="manage_shop"),
    path("staff/products/", ManageProducts.as_view(),
         name="manage_products"),
    path("staff/c/<category>/",
         ManageProducts.as_view(), name="manage_products_by_category"),
    path("staff/d/<department>/",
         ManageProducts.as_view(), name="manage_products_by_department"),
    path("staff/category/new/", CategoryCreate.as_view(),
         name="category_create"),
    path("staff/category/<int:pk>/delete/",
         CategoryDelete.as_view(), name="category_delete"),
    path("staff/category/<int:pk>/update/", CategoryUpdate.as_view(),
         name="category_update"),
    path("staff/product/<slug:slug>/update/",
         ProductUpdate.as_view(), name="product_update"),
    path("staff/coffee/<slug:slug>/update/",
         CoffeeUpdate.as_view(), name="coffee_update"),
    path("staff/new/product", ProductCreate.as_view(), name="product_create"),
    path("staff/new/coffee", CoffeeCreate.as_view(), name="coffee_create"),
    path("staff/product/<int:pk>/delete/",
         ProductDelete.as_view(), name="product_delete"),
]
