from django.urls import path
from .views import (ProductsListView, ProductUpdateView,
                    CoffeeUpdateView, DepartmentCreateView, DepartmentDeleteView,
                    DepartmentUpdateView, ManageShopView, product_detail,
                    ProductCreateView, CategoryDeleteView, CategoryUpdateView,
                    CategoryCreateView, CoffeeCreateView, ProductDeleteView,
                    ManageProductsView, BrandCreateView, BrandUpdateView, BrandDeleteView)

urlpatterns = [
    path("", ProductsListView.as_view(), name="products"),
    path("c/<category>/",
         ProductsListView.as_view(), name="products_by_category"),
    path("d/<department>/",
         ProductsListView.as_view(), name="products_by_department"),
    path("b/<brand>/",
         ProductsListView.as_view(), name="products_by_brand"),
    path("item/<slug:slug>", product_detail, name="product_detail"),
    path("staff/department/new/", DepartmentCreateView.as_view(),
         name="department_create"),
    path("staff/department/<int:pk>/delete/",
         DepartmentDeleteView.as_view(), name="department_delete"),
    path("staff/department/<int:pk>/update/", DepartmentUpdateView.as_view(),
         name="department_update"),
    path("staff/", ManageShopView.as_view(),
         name="manage_shop"),
    path("staff/products/", ManageProductsView.as_view(),
         name="manage_products"),
    path("staff/c/<category>/",
         ManageProductsView.as_view(), name="manage_products_by_category"),
    path("staff/d/<department>/",
         ManageProductsView.as_view(), name="manage_products_by_department"),
    path("staff/category/new/", CategoryCreateView.as_view(),
         name="category_create"),
    path("staff/category/<int:pk>/delete/",
         CategoryDeleteView.as_view(), name="category_delete"),
    path("staff/category/<int:pk>/update/", CategoryUpdateView.as_view(),
         name="category_update"),
    path("staff/brand/new/", BrandCreateView.as_view(),
         name="brand_create"),
    path("staff/brand/<int:pk>/delete/",
         BrandDeleteView.as_view(), name="brand_delete"),
    path("staff/brand/<int:pk>/update/", BrandUpdateView.as_view(),
         name="brand_update"),
    path("staff/product/<slug:slug>/update/",
         ProductUpdateView.as_view(), name="product_update"),
    path("staff/coffee/<slug:slug>/update/",
         CoffeeUpdateView.as_view(), name="coffee_update"),
    path("staff/new/product", ProductCreateView.as_view(),
         name="product_create"),
    path("staff/new/coffee", CoffeeCreateView.as_view(), name="coffee_create"),
    path("staff/product/<int:pk>/delete/",
         ProductDeleteView.as_view(), name="product_delete"),
]
