# Generated by Django 4.1.7 on 2023-02-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_items_cartitem_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='grind_size',
            field=models.CharField(blank=True, choices=[('Wholebean', 'Wholebean'), ('Moka Pot', 'Moka Pot'), ('French Press', 'French Press'), ('Pour Over', 'Pour Over'), ('Filter/Drip', 'Filter/Drip'), ('Espresso', 'Espresso')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='cart.cart'),
        ),
    ]
