# Generated by Django 4.1.7 on 2023-03-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_grind_size_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stripe_payment_intent',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
