# Generated by Django 4.1.7 on 2023-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
