# Generated by Django 4.1.7 on 2023-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_stripe_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='stripe_payment_intent',
        ),
    ]
