# Generated by Django 4.1.7 on 2023-03-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_session_id_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_id',
            new_name='guest_id',
        ),
    ]
