# Generated by Django 4.1.5 on 2023-01-27 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        choices=[("250g", "250g"), ("1kg", "1kg")], max_length=24
                    ),
                ),
                (
                    "grind",
                    models.CharField(
                        choices=[
                            ("Wholebean", "Wholebean"),
                            ("Aeropress", "Aeropress"),
                            ("French Press", "French Press"),
                            ("Filter / Drip", "Filter / Drip"),
                            ("Moka Pot", "Moka Pot"),
                            ("Espresso", "Espresso"),
                        ],
                        max_length=24,
                    ),
                ),
                ("country", models.CharField(max_length=24)),
                ("process", models.CharField(max_length=24)),
                ("harvest_year", models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("visible_to_customers", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=254)),
                ("description", models.TextField()),
                ("sku", models.CharField(blank=True, max_length=254, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("stock", models.PositiveSmallIntegerField()),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                ("image", models.ManyToManyField(to="products.image")),
                (
                    "wish_lists",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wish_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
