# Generated by Django 4.1.5 on 2023-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(blank=True, null=True, to="products.image"),
        ),
    ]
