# Generated by Django 4.1.5 on 2023-02-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_coffee_options_remove_coffee_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coffee",
            options={"verbose_name_plural": "Coffee"},
        ),
        migrations.RemoveField(
            model_name="coffee",
            name="weight",
        ),
    ]
