# Generated by Django 4.1.5 on 2023-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_coffee_options_remove_coffee_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(blank=True, null=True, to="products.image"),
        ),
    ]
