# Generated by Django 4.1.5 on 2023-02-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coffee",
            name="grind",
        ),
        migrations.AddField(
            model_name="coffee",
            name="weight",
            field=models.CharField(
                choices=[("250g", "250g"), ("1kg", "1kg")],
                default="250g",
                max_length=24,
            ),
            preserve_default=False,
        ),
    ]
