# Generated by Django 4.1.7 on 2023-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifetime_sales',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
