# Generated by Django 4.1.7 on 2023-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_lifetime_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lifetime_sales',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, unique=True),
        ),
    ]
